/* Generated By:JJTree: Do not edit this line. CPP2M_id_expression.java */

public class CPP2M_id_expression extends SimpleNode {
  public CPP2M_id_expression(int id) {
    super(id);
  }

  public CPP2M_id_expression(CPPParser p, int id) {
    super(p, id);
  }
  
  /*
  public String process(String prefix) {
  	System.out.println("Error: "+_token.image);
  	return "";
  }
  */
}
