/* Generated By:JJTree: Do not edit this line. CPP2M_superclass_init.java */

public class CPP2M_superclass_init extends SimpleNode {
  public CPP2M_superclass_init(int id) {
    super(id);
  }

  public CPP2M_superclass_init(CPPParser p, int id) {
    super(p, id);
  }

}
