import java.util.Vector;

/* Generated By:JJTree: Do not edit this line. CPP2M_nary_expression.java */

public class CPP2M_nary_expression extends SimpleNode {
  public CPP2M_nary_expression(int id) {
    super(id);
  }

  public CPP2M_nary_expression(CPPParser p, int id) {
    super(p, id);
  }

  public static final int HEIGHT = 20, WIDTH = 20, DEPLX = 50, DEPLY = 50, BASE = 5;
  
  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
  	if (n==1)
  		return ((SimpleNode) this.jjtGetChild(0)).process(prefix);
  	else if (!blocks.isEmpty()) { 		
  		Block helper = (Block)blocks.get(0);
  		String op = add_block(prefix, helper.getComponentName(), helper.getBlockName(),
	              (helper.getOptions()=="" ? "" : helper.getOptions() + ", ") 
				  + "'Position', [" + scope.blockProperties.expX + " "
				  + (scope.blockProperties.expY+BASE) + " "
				  + (scope.blockProperties.expX+WIDTH) + " "
				  + (scope.blockProperties.expY+BASE+(n-1)*HEIGHT) + "]", 
				  false);  		 
		scope.blockProperties.expX -= DEPLX;
  		for(int i=0; i<n; i++) {
  			String out = ((SimpleNode)this.jjtGetChild(i)).process(prefix);
  			scope.blockProperties.expY += DEPLY;
	  		if (out!="")
	  			add_line(prefix, out + "/1", op + "/" + (i+1), null);
	  		else 
	  			System.out.println("error in nary");
  		}
		scope.blockProperties.expX += DEPLX;
  		return op;
  	}
  	else
  		throw new Exception("Unexpected number of child nodes.");
  }
  
  /**
   * Block management for Matlab (add_block, add_line, set_param) 
   */
  protected Vector blocks = null;
  
  public void addBlock(Block block) {
  	if (this.blocks == null)
  		blocks = new Vector();
  	if (block != null)
  		blocks.add(block);
  }
  
  public String toString() { 
  	return CPPParserTreeConstants.jjtNodeName[id] + 
  		   ((this.jjtGetNumChildren() != 0) ? " [" + this.jjtGetNumChildren() + "]" : "") +
		   ((blocks != null && !blocks.isEmpty()) ? " == " + ((Block)blocks.get(0)).getOptions() : ""); 
  }  
}
