/* Generated By:JJTree: Do not edit this line. CPP2M_assignment_expression.java */

public class CPP2M_assignment_expression extends SimpleNode {
  public CPP2M_assignment_expression(int id) {
    super(id);
  }

  public CPP2M_assignment_expression(CPPParser p, int id) {
    super(p, id);
  }
  
  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
  	String in = "", out = "";
  	if (n == 1)
  		in = ((SimpleNode)this.jjtGetChild(0)).process(prefix); 
  	else if (n == 2) {
  		out = ((SimpleNode)this.jjtGetChild(0)).process(prefix);
  		in  = ((SimpleNode)this.jjtGetChild(1)).process(prefix);
  		if (out!="" && in!="")
  			add_line(prefix, in + "/1", out + "/1", null);	
  	}
  	return in;
  }

}
