/* Generated By:JJTree: Do not edit this line. CPP2M_initializer.java */

public class CPP2M_initializer extends SimpleNode {
  public CPP2M_initializer(int id) {
    super(id);
  }

  public CPP2M_initializer(CPPParser p, int id) {
    super(p, id);
  }

}
