/* Generated By:JJTree: Do not edit this line. CPP2M_conversion_function_decl_or_def.java */

public class CPP2M_conversion_function_decl_or_def extends SimpleNode {
  public CPP2M_conversion_function_decl_or_def(int id) {
    super(id);
  }

  public CPP2M_conversion_function_decl_or_def(CPPParser p, int id) {
    super(p, id);
  }

}
