/* Generated By:JJTree: Do not edit this line. CPP2M_type_modifiers.java */

public class CPP2M_type_modifiers extends SimpleNode {
  public CPP2M_type_modifiers(int id) {
    super(id);
  }

  public CPP2M_type_modifiers(CPPParser p, int id) {
    super(p, id);
  }

}
