/* Generated By:JJTree: Do not edit this line. CPP2M_optor.java */

public class CPP2M_optor extends SimpleNode {
  public CPP2M_optor(int id) {
    super(id);
  }

  public CPP2M_optor(CPPParser p, int id) {
    super(p, id);
  }

}
