/* Generated By:JJTree: Do not edit this line. CPP2M_template_parameter.java */

public class CPP2M_template_parameter extends SimpleNode {
  public CPP2M_template_parameter(int id) {
    super(id);
  }

  public CPP2M_template_parameter(CPPParser p, int id) {
    super(p, id);
  }

}
