/* Generated By:JJTree: Do not edit this line. CPP2M_template_head.java */

public class CPP2M_template_head extends SimpleNode {
  public CPP2M_template_head(int id) {
    super(id);
  }

  public CPP2M_template_head(CPPParser p, int id) {
    super(p, id);
  }

}
