/* Generated By:JJTree: Do not edit this line. CPP2M_qualified_type.java */

public class CPP2M_qualified_type extends SimpleNode {
  public CPP2M_qualified_type(int id) {
    super(id);
  }

  public CPP2M_qualified_type(CPPParser p, int id) {
    super(p, id);
  }

}
