/* Generated By:JJTree: Do not edit this line. CPP2M_external_declaration.java */

public class CPP2M_external_declaration extends SimpleNode {
  public CPP2M_external_declaration(int id) {
    super(id);
  }

  public CPP2M_external_declaration(CPPParser p, int id) {
    super(p, id);
  }

}
