/* Generated By:JJTree: Do not edit this line. CPP2M_enumerator.java */

public class CPP2M_enumerator extends SimpleNode {
  public CPP2M_enumerator(int id) {
    super(id);
  }

  public CPP2M_enumerator(CPPParser p, int id) {
    super(p, id);
  }

}
