/* Generated By:JJTree: Do not edit this line. CPP2M_member_declaration.java */

public class CPP2M_member_declaration extends SimpleNode {
  public CPP2M_member_declaration(int id) {
    super(id);
  }

  public CPP2M_member_declaration(CPPParser p, int id) {
    super(p, id);
  }

}
