/* Generated By:JJTree: Do not edit this line. CPP2M_cv_qualifier_seq.java */

public class CPP2M_cv_qualifier_seq extends SimpleNode {
  public CPP2M_cv_qualifier_seq(int id) {
    super(id);
  }

  public CPP2M_cv_qualifier_seq(CPPParser p, int id) {
    super(p, id);
  }

}
