/* Generated By:JJTree: Do not edit this line. CPP2M_iteration_statement.java */

public class CPP2M_iteration_statement extends SimpleNode {
  public CPP2M_iteration_statement(int id) {
    super(id);
  }

  public CPP2M_iteration_statement(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
	if (_token == "for") {
		//String expr = ((SimpleNode) this.jjtGetChild(0)).process(prefix);
		String stmt = ((SimpleNode) this.jjtGetChild(n-1)).process(prefix);
		add_block(prefix + "/" + stmt, "'simulink3/Subsystems/For Iterator Subsystem/For Iterator'", "For ", null, false);
		//add_line(prefix, expr + "/1", stmt + "/For Iterator", null);
	}
  	return "";
  }
}
