/* Generated By:JJTree: Do not edit this line. CPP2M_new_expression.java */

public class CPP2M_new_expression extends SimpleNode {
  public CPP2M_new_expression(int id) {
    super(id);
  }

  public CPP2M_new_expression(CPPParser p, int id) {
    super(p, id);
  }

}
