/* Generated By:JJTree: Do not edit this line. CPP2M_cast_expression.java */

public class CPP2M_cast_expression extends SimpleNode {
  public CPP2M_cast_expression(int id) {
    super(id);
  }

  public CPP2M_cast_expression(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();  	
  	if (n==1)
  		return ((SimpleNode) this.jjtGetChild(0)).process(prefix);
  	else if (n==2)
  		return ((SimpleNode) this.jjtGetChild(1)).process(prefix);
  	else
  		throw new Exception("Unexpected number of child nodes.");
  }
}
