/* Generated By:JJTree: Do not edit this line. CPP2M_base_clause.java */

public class CPP2M_base_clause extends SimpleNode {
  public CPP2M_base_clause(int id) {
    super(id);
  }

  public CPP2M_base_clause(CPPParser p, int id) {
    super(p, id);
  }

}
