import java.util.Vector;

/* Generated By:JJTree: Do not edit this line. CPP2M_binary_expression.java */

public class CPP2M_binary_expression extends SimpleNode {
  public CPP2M_binary_expression(int id) {
    super(id);
  }

  public CPP2M_binary_expression(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
  	if (n==1)
  		return ((SimpleNode) this.jjtGetChild(0)).process(prefix);
  	else if (blocks.size()==n-1) { 		
  		Block helper = (Block)blocks.get(0);
  		String op = add_block(prefix, helper.getComponentName(), helper.getBlockName(),
	              (helper.getOptions()=="" ? "" : helper.getOptions() + ", ") 
				  + "'Position', [" + scope.blockProperties.expX + " "
				  + (scope.blockProperties.expY+5) + " "
				  + (scope.blockProperties.expX+20) + " "
				  + (scope.blockProperties.expY+25) + "]", 
				  false);
  		scope.blockProperties.expX -= 50; 
  		String out1 = ((SimpleNode)this.jjtGetChild(0)).process(prefix);
  		scope.blockProperties.expY += 50;
  		String out2 = ((SimpleNode)this.jjtGetChild(1)).process(prefix);
  		if (out1!="")
  			add_line(prefix, out1 + "/1", op + "/1", null);
  		if (out2!="")
  			add_line(prefix, out2 + "/1", op + "/2", null);
  		scope.blockProperties.expX += 50; 
  		return op;
  	}
  	else
  		throw new Exception("Unexpected number of child nodes.");
  }
  
  /**
   * Block management for Matlab (add_block, add_line, set_param) 
   */
  protected Vector blocks = null;
  
  public void addBlock(Block block) {
  	if (this.blocks == null)
  		blocks = new Vector();
  	if (block != null)
  		blocks.add(block);
  }
  
  public String toString() { 
  	return CPPParserTreeConstants.jjtNodeName[id] + 
  		   ((this.jjtGetNumChildren() != 0) ? " [" + this.jjtGetNumChildren() + "]" : "") +
		   ((blocks != null && !blocks.isEmpty()) ? " == " + ((Block)blocks.get(0)).getOptions() : ""); 
  }  
}
