/* Generated By:JJTree: Do not edit this line. CPP2M_abstract_declarator_suffix.java */

public class CPP2M_abstract_declarator_suffix extends SimpleNode {
  public CPP2M_abstract_declarator_suffix(int id) {
    super(id);
  }

  public CPP2M_abstract_declarator_suffix(CPPParser p, int id) {
    super(p, id);
  }

}
