/* Generated By:JJTree: Do not edit this line. CPP2M_statement.java */

public class CPP2M_statement extends SimpleNode {
  public CPP2M_statement(int id) {
    super(id);
  }

  public CPP2M_statement(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
  	
  	scope.blockProperties.resetPositions(false);

  	String out = "";
  	if (n==1)
  		out = ((SimpleNode) this.jjtGetChild(0)).process(prefix);
  	else {
  		for (int i = 0; i < n; ++i) {
  			SimpleNode c = (SimpleNode)children[i];
  			if (c != null)
  				c.process(prefix);
  		}
  	}
  	return out;
  }
}
