/* Generated By:JJTree: Do not edit this line. CPP2M_scope_override.java */

public class CPP2M_scope_override extends SimpleNode {
  public CPP2M_scope_override(int id) {
    super(id);
  }

  public CPP2M_scope_override(CPPParser p, int id) {
    super(p, id);
  }

}
