/* Generated By:JJTree: Do not edit this line. CPP2M_template_argument.java */

public class CPP2M_template_argument extends SimpleNode {
  public CPP2M_template_argument(int id) {
    super(id);
  }

  public CPP2M_template_argument(CPPParser p, int id) {
    super(p, id);
  }

}
