/* Generated By:JJTree: Do not edit this line. CPP2M_linkage_specification.java */

public class CPP2M_linkage_specification extends SimpleNode {
  public CPP2M_linkage_specification(int id) {
    super(id);
  }

  public CPP2M_linkage_specification(CPPParser p, int id) {
    super(p, id);
  }

}
