/* Generated By:JJTree: Do not edit this line. CPP2M_declaration.java */

public class CPP2M_declaration extends SimpleNode {
  public CPP2M_declaration(int id) {
    super(id);
  }

  public CPP2M_declaration(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	/*
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();
  	if(!stop)
  		for (int i = 0; i < n; ++i) {
  			SimpleNode c = (SimpleNode)children[i];
  			if (c != null)
  				c.process(prefix);
  		}
  	*/
  	return "";
  }  
}
