/* Generated By:JJTree: Do not edit this line. CPP2M_dtor_ctor_decl_spec.java */

public class CPP2M_dtor_ctor_decl_spec extends SimpleNode {
  public CPP2M_dtor_ctor_decl_spec(int id) {
    super(id);
  }

  public CPP2M_dtor_ctor_decl_spec(CPPParser p, int id) {
    super(p, id);
  }

}
