/* Generated By:JJTree: Do not edit this line. CPP2M_try_block.java */

public class CPP2M_try_block extends SimpleNode {
  public CPP2M_try_block(int id) {
    super(id);
  }

  public CPP2M_try_block(CPPParser p, int id) {
    super(p, id);
  }

}
