/* Generated By:JJTree: Do not edit this line. CPP2M_statement_list.java */

public class CPP2M_statement_list extends SimpleNode {
  public CPP2M_statement_list(int id) {
    super(id);
  }

  public CPP2M_statement_list(CPPParser p, int id) {
    super(p, id);
  }

}
