/* Generated By:JJTree: Do not edit this line. CPP2M_declaration_specifiers.java */

public class CPP2M_declaration_specifiers extends SimpleNode {
  public CPP2M_declaration_specifiers(int id) {
    super(id);
  }

  public CPP2M_declaration_specifiers(CPPParser p, int id) {
    super(p, id);
  }

}
