/* Generated By:JJTree: Do not edit this line. CPP2M_ptr_operator.java */

public class CPP2M_ptr_operator extends SimpleNode {
  public CPP2M_ptr_operator(int id) {
    super(id);
  }

  public CPP2M_ptr_operator(CPPParser p, int id) {
    super(p, id);
  }

}
