/* Generated By:JJTree: Do not edit this line. CPP2M_init_declarator.java */

public class CPP2M_init_declarator extends SimpleNode {
  public CPP2M_init_declarator(int id) {
    super(id);
  }

  public CPP2M_init_declarator(CPPParser p, int id) {
    super(p, id);
  }

}
