/* Generated By:JJTree: Do not edit this line. CPP2M_handler.java */

public class CPP2M_handler extends SimpleNode {
  public CPP2M_handler(int id) {
    super(id);
  }

  public CPP2M_handler(CPPParser p, int id) {
    super(p, id);
  }

}
