/* Generated By:JJTree: Do not edit this line. CPP2M_throw_statement.java */

public class CPP2M_throw_statement extends SimpleNode {
  public CPP2M_throw_statement(int id) {
    super(id);
  }

  public CPP2M_throw_statement(CPPParser p, int id) {
    super(p, id);
  }

}
