/* Generated By:JJTree: Do not edit this line. CPP2M_new_type_id.java */

public class CPP2M_new_type_id extends SimpleNode {
  public CPP2M_new_type_id(int id) {
    super(id);
  }

  public CPP2M_new_type_id(CPPParser p, int id) {
    super(p, id);
  }

}
