/* Generated By:JJTree: Do not edit this line. CPP2M_declarator_suffixes.java */

public class CPP2M_declarator_suffixes extends SimpleNode {
  public CPP2M_declarator_suffixes(int id) {
    super(id);
  }

  public CPP2M_declarator_suffixes(CPPParser p, int id) {
    super(p, id);
  }

}
