/* Generated By:JJTree: Do not edit this line. CPP2M_func_decl_def.java */

public class CPP2M_func_decl_def extends SimpleNode {
  public CPP2M_func_decl_def(int id) {
    super(id);
  }

  public CPP2M_func_decl_def(CPPParser p, int id) {
    super(p, id);
  }

}
