/* Generated By:JJTree: Do not edit this line. CPP2M_type_qualifier.java */

public class CPP2M_type_qualifier extends SimpleNode {
  public CPP2M_type_qualifier(int id) {
    super(id);
  }

  public CPP2M_type_qualifier(CPPParser p, int id) {
    super(p, id);
  }

}
