/* Generated By:JJTree: Do not edit this line. CPP2M_ctor_declarator_lookahead.java */

public class CPP2M_ctor_declarator_lookahead extends SimpleNode {
  public CPP2M_ctor_declarator_lookahead(int id) {
    super(id);
  }

  public CPP2M_ctor_declarator_lookahead(CPPParser p, int id) {
    super(p, id);
  }

}
