/* Generated By:JJTree: Do not edit this line. CPP2M_jump_statement.java */

public class CPP2M_jump_statement extends SimpleNode {
  public CPP2M_jump_statement(int id) {
    super(id);
  }

  public CPP2M_jump_statement(CPPParser p, int id) {
    super(p, id);
  }

  public String process(String prefix) throws Exception {
  	int n = this.jjtGetNumChildren();
  	prefix = scope.toString();  	
  	if (_token == "return" && n==1 ) {
  		String expr = ((SimpleNode) this.jjtGetChild(0)).process(prefix); 
		String out  = add_block(prefix, "'built-in/OutPort'", "Return ", 
		        "'Position', [" + scope.blockProperties.outX + " " 
			                + scope.blockProperties.outY + " " 
							+ (scope.blockProperties.outX+30) + " " 
							+ (scope.blockProperties.outY+15) 
						    + "]", 
			true);
  		scope.blockProperties.outY += 50;
  		if(expr != "" && expr != null)
  			add_line(prefix, expr + "/1", out + "/1", null);  		
  		return ""; 
  	}
  	else 
  		throw new Exception("Unexpected number of child nodes.");
  }
}
