/* Generated By:JJTree: Do not edit this line. CPP2M_base_specifier.java */

public class CPP2M_base_specifier extends SimpleNode {
  public CPP2M_base_specifier(int id) {
    super(id);
  }

  public CPP2M_base_specifier(CPPParser p, int id) {
    super(p, id);
  }

}
