/* Generated By:JJTree: Do not edit this line. CPP2M_ctor_definition.java */

public class CPP2M_ctor_definition extends SimpleNode {
  public CPP2M_ctor_definition(int id) {
    super(id);
  }

  public CPP2M_ctor_definition(CPPParser p, int id) {
    super(p, id);
  }

}
