/* Generated By:JJTree: Do not edit this line. CPP2M_ptr_to_member.java */

public class CPP2M_ptr_to_member extends SimpleNode {
  public CPP2M_ptr_to_member(int id) {
    super(id);
  }

  public CPP2M_ptr_to_member(CPPParser p, int id) {
    super(p, id);
  }

}
