/* Generated By:JJTree: Do not edit this line. CPP2M_type_name.java */

public class CPP2M_type_name extends SimpleNode {
  public CPP2M_type_name(int id) {
    super(id);
  }

  public CPP2M_type_name(CPPParser p, int id) {
    super(p, id);
  }

}
