/* Generated By:JJTree: Do not edit this line. CPPParserTreeConstants.java */

public interface CPPParserTreeConstants
{
  public int JJTTRANSLATION_UNIT = 0;
  public int JJTEXTERNAL_DECLARATION = 1;
  public int JJTFUNCTION_DEFINITION = 2;
  public int JJTFUNC_DECL_DEF = 3;
  public int JJTLINKAGE_SPECIFICATION = 4;
  public int JJTDECLARATION = 5;
  public int JJTTYPE_MODIFIERS = 6;
  public int JJTDECLARATION_SPECIFIERS = 7;
  public int JJTSIMPLE_TYPE_SPECIFIER = 8;
  public int JJTSCOPE_OVERRIDE_LOOKAHEAD = 9;
  public int JJTSCOPE_OVERRIDE = 10;
  public int JJTQUALIFIED_ID = 11;
  public int JJTPTR_TO_MEMBER = 12;
  public int JJTQUALIFIED_TYPE = 13;
  public int JJTTYPE_QUALIFIER = 14;
  public int JJTSTORAGE_CLASS_SPECIFIER = 15;
  public int JJTBUILTIN_TYPE_SPECIFIER = 16;
  public int JJTINIT_DECLARATOR_LIST = 17;
  public int JJTINIT_DECLARATOR = 18;
  public int JJTCLASS_HEAD = 19;
  public int JJTCLASS_SPECIFIER = 20;
  public int JJTBASE_CLAUSE = 21;
  public int JJTBASE_SPECIFIER = 22;
  public int JJTACCESS_SPECIFIER = 23;
  public int JJTMEMBER_DECLARATION = 24;
  public int JJTMEMBER_DECLARATOR_LIST = 25;
  public int JJTMEMBER_DECLARATOR = 26;
  public int JJTCONVERSION_FUNCTION_DECL_OR_DEF = 27;
  public int JJTENUM_SPECIFIER = 28;
  public int JJTENUMERATOR_LIST = 29;
  public int JJTENUMERATOR = 30;
  public int JJTPTR_OPERATOR = 31;
  public int JJTCV_QUALIFIER_SEQ = 32;
  public int JJTDECLARATOR = 33;
  public int JJTDIRECT_DECLARATOR = 34;
  public int JJTDECLARATOR_SUFFIXES = 35;
  public int JJTFUNCTION_DECLARATOR_LOOKAHEAD = 36;
  public int JJTFUNCTION_DECLARATOR = 37;
  public int JJTFUNCTION_DIRECT_DECLARATOR = 38;
  public int JJTDTOR_CTOR_DECL_SPEC = 39;
  public int JJTDTOR_DEFINITION = 40;
  public int JJTCTOR_DEFINITION = 41;
  public int JJTCTOR_DECLARATOR_LOOKAHEAD = 42;
  public int JJTCTOR_DECLARATOR = 43;
  public int JJTCTOR_INITIALIZER = 44;
  public int JJTSUPERCLASS_INIT = 45;
  public int JJTDTOR_DECLARATOR = 46;
  public int JJTSIMPLE_DTOR_DECLARATOR = 47;
  public int JJTPARAMETER_LIST = 48;
  public int JJTPARAMETER_DECLARATION_LIST = 49;
  public int JJTPARAMETER_DECLARATION = 50;
  public int JJTINITIALIZER = 51;
  public int JJTTYPE_NAME = 52;
  public int JJTABSTRACT_DECLARATOR = 53;
  public int JJTABSTRACT_DECLARATOR_SUFFIX = 54;
  public int JJTTEMPLATE_HEAD = 55;
  public int JJTTEMPLATE_PARAMETER_LIST = 56;
  public int JJTTEMPLATE_PARAMETER = 57;
  public int JJTTEMPLATE_ID = 58;
  public int JJTTEMPLATE_ARGUMENT_LIST = 59;
  public int JJTTEMPLATE_ARGUMENT = 60;
  public int JJTSTATEMENT_LIST = 61;
  public int JJTSTATEMENT = 62;
  public int JJTLABELED_STATEMENT = 63;
  public int JJTCOMPOUND_STATEMENT = 64;
  public int JJTSELECTION_STATEMENT = 65;
  public int JJTITERATION_STATEMENT = 66;
  public int JJTJUMP_STATEMENT = 67;
  public int JJTTRY_BLOCK = 68;
  public int JJTHANDLER = 69;
  public int JJTEXCEPTION_DECLARATION = 70;
  public int JJTTHROW_STATEMENT = 71;
  public int JJTEXPRESSION = 72;
  public int JJTASSIGNMENT_EXPRESSION = 73;
  public int JJTCONDITIONAL_EXPRESSION = 74;
  public int JJTCONSTANT_EXPRESSION = 75;
  public int JJTNARY_EXPRESSION = 76;
  public int JJTBINARY_EXPRESSION = 77;
  public int JJTEXCLUSIVE_OR_EXPRESSION = 78;
  public int JJTPM_EXPRESSION = 79;
  public int JJTCAST_EXPRESSION = 80;
  public int JJTUNARY_EXPRESSION = 81;
  public int JJTNEW_EXPRESSION = 82;
  public int JJTNEW_TYPE_ID = 83;
  public int JJTNEW_DECLARATOR = 84;
  public int JJTDIRECT_NEW_DECLARATOR = 85;
  public int JJTNEW_INITIALIZER = 86;
  public int JJTDELETE_EXPRESSION = 87;
  public int JJTUNARY_OPERATOR = 88;
  public int JJTPOSTFIX_EXPRESSION = 89;
  public int JJTID_EXPRESSION = 90;
  public int JJTPRIMARY_EXPRESSION = 91;
  public int JJTEXPRESSION_LIST = 92;
  public int JJTCONSTANT = 93;
  public int JJTOPTOR = 94;
  public int JJTEXCEPTION_SPEC = 95;
  public int JJTEXCEPTION_LIST = 96;


  public String[] jjtNodeName = {
    "translation_unit",
    "external_declaration",
    "function_definition",
    "func_decl_def",
    "linkage_specification",
    "declaration",
    "type_modifiers",
    "declaration_specifiers",
    "simple_type_specifier",
    "scope_override_lookahead",
    "scope_override",
    "qualified_id",
    "ptr_to_member",
    "qualified_type",
    "type_qualifier",
    "storage_class_specifier",
    "builtin_type_specifier",
    "init_declarator_list",
    "init_declarator",
    "class_head",
    "class_specifier",
    "base_clause",
    "base_specifier",
    "access_specifier",
    "member_declaration",
    "member_declarator_list",
    "member_declarator",
    "conversion_function_decl_or_def",
    "enum_specifier",
    "enumerator_list",
    "enumerator",
    "ptr_operator",
    "cv_qualifier_seq",
    "declarator",
    "direct_declarator",
    "declarator_suffixes",
    "function_declarator_lookahead",
    "function_declarator",
    "function_direct_declarator",
    "dtor_ctor_decl_spec",
    "dtor_definition",
    "ctor_definition",
    "ctor_declarator_lookahead",
    "ctor_declarator",
    "ctor_initializer",
    "superclass_init",
    "dtor_declarator",
    "simple_dtor_declarator",
    "parameter_list",
    "parameter_declaration_list",
    "parameter_declaration",
    "initializer",
    "type_name",
    "abstract_declarator",
    "abstract_declarator_suffix",
    "template_head",
    "template_parameter_list",
    "template_parameter",
    "template_id",
    "template_argument_list",
    "template_argument",
    "statement_list",
    "statement",
    "labeled_statement",
    "compound_statement",
    "selection_statement",
    "iteration_statement",
    "jump_statement",
    "try_block",
    "handler",
    "exception_declaration",
    "throw_statement",
    "expression",
    "assignment_expression",
    "conditional_expression",
    "constant_expression",
    "nary_expression",
    "binary_expression",
    "exclusive_or_expression",
    "pm_expression",
    "cast_expression",
    "unary_expression",
    "new_expression",
    "new_type_id",
    "new_declarator",
    "direct_new_declarator",
    "new_initializer",
    "delete_expression",
    "unary_operator",
    "postfix_expression",
    "id_expression",
    "primary_expression",
    "expression_list",
    "constant",
    "optor",
    "exception_spec",
    "exception_list",
  };
}
