/* Generated By:JJTree&JavaCC: Do not edit this line. CPPParserConstants.java */
public interface CPPParserConstants {

  int EOF = 0;
  int LCURLYBRACE = 10;
  int RCURLYBRACE = 11;
  int LSQUAREBRACKET = 12;
  int RSQUAREBRACKET = 13;
  int LPARENTHESIS = 14;
  int RPARENTHESIS = 15;
  int SCOPE = 16;
  int COLON = 17;
  int SEMICOLON = 18;
  int COMMA = 19;
  int QUESTIONMARK = 20;
  int ELLIPSIS = 21;
  int ASSIGNEQUAL = 22;
  int TIMESEQUAL = 23;
  int DIVIDEEQUAL = 24;
  int MODEQUAL = 25;
  int PLUSEQUAL = 26;
  int MINUSEQUAL = 27;
  int SHIFTLEFTEQUAL = 28;
  int SHIFTRIGHTEQUAL = 29;
  int BITWISEANDEQUAL = 30;
  int BITWISEXOREQUAL = 31;
  int BITWISEOREQUAL = 32;
  int OR = 33;
  int AND = 34;
  int BITWISEOR = 35;
  int BITWISEXOR = 36;
  int AMPERSAND = 37;
  int EQUAL = 38;
  int NOTEQUAL = 39;
  int LESSTHAN = 40;
  int GREATERTHAN = 41;
  int LESSTHANOREQUALTO = 42;
  int GREATERTHANOREQUALTO = 43;
  int SHIFTLEFT = 44;
  int SHIFTRIGHT = 45;
  int PLUS = 46;
  int MINUS = 47;
  int STAR = 48;
  int DIVIDE = 49;
  int MOD = 50;
  int PLUSPLUS = 51;
  int MINUSMINUS = 52;
  int TILDE = 53;
  int NOT = 54;
  int DOT = 55;
  int POINTERTO = 56;
  int DOTSTAR = 57;
  int ARROWSTAR = 58;
  int AUTO = 59;
  int BREAK = 60;
  int CASE = 61;
  int CATCH = 62;
  int CHAR = 63;
  int CONST = 64;
  int CONTINUE = 65;
  int _DEFAULT = 66;
  int DELETE = 67;
  int DO = 68;
  int DOUBLE = 69;
  int ELSE = 70;
  int ENUM = 71;
  int EXTERN = 72;
  int FLOAT = 73;
  int FOR = 74;
  int FRIEND = 75;
  int GOTO = 76;
  int IF = 77;
  int INLINE = 78;
  int INT = 79;
  int LONG = 80;
  int NEW = 81;
  int PRIVATE = 82;
  int PROTECTED = 83;
  int PUBLIC = 84;
  int REDECLARED = 85;
  int REGISTER = 86;
  int RETURN = 87;
  int SHORT = 88;
  int SIGNED = 89;
  int SIZEOF = 90;
  int STATIC = 91;
  int STRUCT = 92;
  int CLASS = 93;
  int SWITCH = 94;
  int TEMPLATE = 95;
  int THIS = 96;
  int TRY = 97;
  int TYPEDEF = 98;
  int UNION = 99;
  int UNSIGNED = 100;
  int VIRTUAL = 101;
  int VOID = 102;
  int VOLATILE = 103;
  int WHILE = 104;
  int OPERATOR = 105;
  int TRUETOK = 106;
  int FALSETOK = 107;
  int THROW = 108;
  int OCTALINT = 109;
  int OCTALLONG = 110;
  int UNSIGNED_OCTALINT = 111;
  int UNSIGNED_OCTALLONG = 112;
  int DECIMALINT = 113;
  int DECIMALLONG = 114;
  int UNSIGNED_DECIMALINT = 115;
  int UNSIGNED_DECIMALLONG = 116;
  int HEXADECIMALINT = 117;
  int HEXADECIMALLONG = 118;
  int UNSIGNED_HEXADECIMALINT = 119;
  int UNSIGNED_HEXADECIMALLONG = 120;
  int FLOATONE = 121;
  int FLOATTWO = 122;
  int CHARACTER = 123;
  int STRING = 124;
  int ID = 126;

  int DEFAULT = 0;
  int PREPROCESSOR_OUTPUT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"#\"",
    "\"\\n\"",
    "<token of kind 9>",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"::\"",
    "\":\"",
    "\";\"",
    "\",\"",
    "\"?\"",
    "\"...\"",
    "\"=\"",
    "\"*=\"",
    "\"/=\"",
    "\"%=\"",
    "\"+=\"",
    "\"-=\"",
    "\"<<=\"",
    "\">>=\"",
    "\"&=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&&\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"++\"",
    "\"--\"",
    "\"~\"",
    "\"!\"",
    "\".\"",
    "\"->\"",
    "\".*\"",
    "\"->*\"",
    "\"auto\"",
    "\"break\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"delete\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extern\"",
    "\"float\"",
    "\"for\"",
    "\"friend\"",
    "\"goto\"",
    "\"if\"",
    "\"inline\"",
    "\"int\"",
    "\"long\"",
    "\"new\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"redeclared\"",
    "\"register\"",
    "\"return\"",
    "\"short\"",
    "\"signed\"",
    "\"sizeof\"",
    "\"static\"",
    "\"struct\"",
    "\"class\"",
    "\"switch\"",
    "\"template\"",
    "\"this\"",
    "\"try\"",
    "\"typedef\"",
    "\"union\"",
    "\"unsigned\"",
    "\"virtual\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"operator\"",
    "\"true\"",
    "\"false\"",
    "\"throw\"",
    "<OCTALINT>",
    "<OCTALLONG>",
    "<UNSIGNED_OCTALINT>",
    "<UNSIGNED_OCTALLONG>",
    "<DECIMALINT>",
    "<DECIMALLONG>",
    "<UNSIGNED_DECIMALINT>",
    "<UNSIGNED_DECIMALLONG>",
    "<HEXADECIMALINT>",
    "<HEXADECIMALLONG>",
    "<UNSIGNED_HEXADECIMALINT>",
    "<UNSIGNED_HEXADECIMALLONG>",
    "<FLOATONE>",
    "<FLOATTWO>",
    "<CHARACTER>",
    "<STRING>",
    "\"finally\"",
    "<ID>",
  };

}
